### ISSUE TITLE
Keywords in metadata; is there anything we can do to make this used in a consistent way and promote searchability

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederationDataStore/about_the_data_store#34]
not on warpath (yet), but entering the issue in response to some SNAFUs in the new gene family README with a few not-really-scientific-names in the list:
Cicar arietinum, Lupinus angularis

@cann0010 may want to clean those at his leisure.

**Comment by cann0010** [comment]
Oops. Fixed (in local DS and at CyVerse). I updated the REAME and the CHECKSUM file.

**Comment by adf-ncgr** [comment]
thanks- I'd still like to leave this open until we have some general recommendations in place on how this field should be populated. Examples taken at random (see below) suggest that there are some patterns, but that some work could be done to improve consistency+accuracy; also, when I did the bulk uploading of the medicago hapmap genomes I really had no idea what the intent was based on the metadata file template, so left as "none"; maybe I'll regret it and revisit, or maybe I won't. only having a plan for what happens to them downstream will point me down one path or another...


public/Arachis_duranensis/V14167.gnm1.SWBf/README.SWBf.md keywords  'Arachis duranensis, genome assembly'
public/Arachis_duranensis/V14167.gnm1.ann1.cxSM/README.cxSM.md keywords 'Arachis duranensis, genome assembly'
public/Arachis_hypogaea/Tifrunner.gnm1.KYV3/README.KYV3.md keywords 'peanut, Arachis hypogaea, Tifrunner'
public/Arachis_hypogaea/Tifrunner.gnm1.ann1.CCJH/README.CCJH.md keywords    'peanut, Arachis hypogaea, Tifrunner'
public/Arachis_hypogaea/Tifrunner.tcp1.sSQ6/README.sSQ6.md keywords 'Transcriptome, gene expression, peanut, Arachis hypogaea'

**Comment by adf-ncgr** [comment]
AFAIK nothing actually uses the keywords, so closing until such time as " a plan for what happens to them downstream" materializes...
