### ISSUE TITLE
RFO: use github versioning to track changes to metadata templates

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederationDataStore/about_the_data_store#35]
We have a file in github:
https://github.com/LegumeFederation/datastore/blob/master/metadata/README.Template_LegFed_2016-12-23.md.txt

which I have been using as the place to make changes; I see now there is an untracked file:
https://legumeinfo.org/data/metadata/README.Template_LegFed_2018-03-23.md.txt

that has probably diverged from the former. It maintains some description of the changes inside, and I guess the date in the file name would suggest it supercedes. But, we need to resolve the issue of how this is going to be maintained to avoid future confusion/divergence. 

open to alternatives, but github seems like a fine place to do versioning on such info...

**Comment by adf-ncgr** [comment]
PS. I'll note that I may be guilty of editing the template through the github editor and committing, but
not refreshing the instances in the sites by a git pull. A possible downside of the proposed approach, but a cron job would probably be sufficient to solve the occasional memory lapse...

**Comment by cann0010** [comment]
No objection. I think the RFO is to make the GitHub instances be the primary/origin ones - which I think means cloning/pulling from GitHub into /usr/local/www/data/metadata/
While we are at it, we should probably remove the date versioning from the files, and maybe rename about_the_data_repository.md --> about_the_Data_Store.md
To adf: do you want to do the honors of cleaning out the local metadata directory and pulling from GitHub? (Or I can do it with some help here - since my git foo is rudimentary)

**Comment by adf-ncgr** [comment]
I'd be honored to do the honors. My own rudimentary git fu is always in need of further training. Note that /usr/local/www/data is already git-ified:
[adf@lis-stage /usr/local/www/data]$ ls -al
total 125
drwxrwxr-x   7 root     staff      9 Feb 16 13:47 .
drwxr-xr-x  16 root     wheel     16 Oct 28 01:01 ..
**drwxrwxr-x   8 adf      staff     16 Mar 31 18:52 .git**
-rw-rw-r--   1 adf      adf    35141 Jul 19  2017 LICENSE
-rw-rw-r--   1 adf      adf      468 Jul 19  2017 README.md
drwxrwxr-x   4 root     staff      7 Feb 15 10:57 _h5ai
drwxrwxr-x   3 scannon  staff      9 Apr 18 08:54 metadata
drwxrwxr-x  34 scannon  staff     34 Mar 21 11:04 private
drwxrwxr-x  20 scannon  staff     21 Mar 21 17:00 public

though not everything beneath is managed under git- nothing under data, as far as I know, though I have wondered if keeping the READMEs under version control might not be appropriate; would require some further thought, but if you think it is worth discussion, I'm game

**Comment by cann0010** [comment]
Actually ... it would be good for me to have the git experience. I'll make the changes - unless you are already doing the work.

**Comment by adf-ncgr** [comment]
the honors are all yours. I just did a git pull to ensure whatever I might have done via the github editor is captured locally; a side effect is that Connor's scripts for doing validation are now appearing here:
https://legumeinfo.org/data/detect_incongruencies/

not sure if that is necessarily a bad thing, but we can suppress (presumably via h5ai config) or change location these are maintained if we'd rather not have this code muddying up the hierarchy
(there are some other scripts under private)

Here's the current git status report which might be a good place for you to start 

[adf@lis-stage /usr/local/www/data]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    metadata/README.Template_LegFed_2016-12-23.md
	modified:   metadata/about_the_registry.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	_h5ai/
	metadata/.zDrafts/
	metadata/MANIFEST.Template_LegFed_2018_04_12.correspondence.txt
	metadata/MANIFEST.Template_LegFed_2018_04_12.descriptions.txt
	metadata/README.Template_LegFed_2018-03-23.md.txt
etc.

let me know if any questions...

**Comment by cann0010** [comment]
OK, I think it's all in sync now.
I updated .gitignore to stop watching private/ and _h5ai/ and updated everything in metadata/
Issue is probably close-able now, after your review.

**Comment by adf-ncgr** [comment]
I think this is basically done; at least, we're in agreement that we should be using github and it
appears everything in about_the_datastore is committed and pushed. Now we just need to keep up the good work...
