### ISSUE TITLE
RFO: standard conventions for macrosynteny naming

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederationDataStore/about_the_data_store#4]
I think someone started to discuss this in an email thread, but moving here for the sake of greater transparency (without digging up the email thread that started it). currently the designations that indicate the genomes being compared are similar to but not identical with our genome naming convention, e.g.:
`Lupinus_angustifolius/Tanjil.gnm1.syn1.TwnC/lupan.Tanjil.a1.x.aradu.V14167.v1.gff.gz`
(note how gnm1 becomes "a1" in the file name and the aradu similarly has gone from Arachis_duranensis/V14167.gnm1.SWBf to "v1") 

moving fwd, I'd propose that we use the same conventions for genome identification in these file names as elsewhere. I'm also curious whether the methods used to produce these are using the
genomes directly or determining synteny via gene model comparisons. If the latter, it would seem more proper to make these "children" of the annotations off of which they've been computed, 
e.g. 
`Lupinus_angustifolius/Tanjil.gnm1.ann1.syn1.TwnC/lupan.Tanjil.gnm1.ann1.x.aradu.V14167.gnm1.ann1`

this would be similar to what we're planning for expression which is relative to an annotation set;
thoughts?

**Comment by adf-ncgr** [comment]
no objections! passed...
wei and I will work on getting some of this into place

**Comment by jd-campbell** [comment]
@adf-ncgr 
For consistency I think it is a good idea to edit the contents of the files so that it matches the fasta header ids in our genome_main files.  I vote that both column 1 IDs and column 9 IDs need to be changed. 

Example: Wm82.gnm2.syn1.HXNY/glyma.Wm82_a2.x.vigan.Gyeongwon_v3.gff.gz 

**Gm01**	DAGchainer	syntenic_region	1459585	1691957	219.0	-	.	Name=**Va**11;matches=**Va**11:2697407..2989425;median_Ks=0.6950
**Gm01**	DAGchainer	syntenic_region	1722270	2067966	1112.2	+	.	Name=**vigan.SuperScaf**_2;matches=**vigan.SuperScaf**_2:3033390..3573512;median_Ks=0.3605

Need to make three files content changes for the two lines above" 
%s/^Gm/glyma.Wm82.gnm2.Gm/
%s/=Va/=vigan.Gyeongwon.gnm3.Va/
%s/=vigan.SuperScaf/=vigan.Gyeongwon.gnm3.SuperScaf/

**Comment by jd-campbell** [comment]
@adf-ncgr I like checklists.  😄 

**Arachis_duranensis/V14167.gnm1.syn1.qmkW/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Arachis_ipaensis/K30076.gnm1.syn1.S8s4/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Cajanus_cajan/ICPL87119.gnm1.syn1.Nkx0/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Cicer_arietinum/CDCFrontier.gnm1.syn1.7Bqh/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Cicer_arietinum/ICC4958.gnm2.syn1.PdvJ/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Glycine_max/Wm82.gnm2.syn1.HXNY/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Lupinus_angustifolius/Tanjil.gnm1.syn1.TwnC/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Phaseolus_vulgaris/G19833.gnm1.syn1.xQ7F/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Phaseolus_vulgaris/G19833.gnm2.syn1.DVDW/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Trifolium_pratense/MilvusB.gnm2.syn1.dXVX/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Vigna_angularis/Gyeongwon.gnm3.syn1.wCFF/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Vigna_radiata/VC1973A.gnm6.syn1.mcwy/**
- [ ] Change Column 1 & Column 9 IDs (E.g. = s/^Gm/glyma.Wm82.gnm2.Gm/)
- [ ] Change file names
- [ ] Create README, MANIFEST & CHECKSUM files (private/test_metadata/template.syn__README.KEY.md.txt)
- [ ] Done at LIS
- [ ] Done at CyVerse

**Comment by jd-campbell** [comment]
Question for @adf-ncgr @cann0010 

Andrew and I discussed earlier in this issue about changing the Column 1 and Column 9 IDs in each synteny gff file. (See comments above.) The question I have is regarding what should be IDs be changed to. 

Andrew mentioned previously changing cicar.CDCFrontier.**v1**.Ca1 to cicar.CDCFrontier.**gnm1**.Ca1, my question is should we include the annotation version in the column ID? ( cicar.CDCFrontier.**gnm1.ann1**.Ca1 )

**Comment by jd-campbell** [comment]
@adf-ncgr -- That is what I was thinking also - that since the macrosynteny calculations are based on the gene models I should mention the annotation version in the column ID.  I already added the annotation version to the file name ( aradu.V14167.gnm1.ann1.x.aradu.V14167.gnm1.ann1.gff ).

**Comment by jd-campbell** [comment]
@adf-ncgr --- I thought of another thing --- 
In the new file names: aradu.V14167.gnm1.ann1.x.glyma.Wm82.gnm2.ann1.gff 
There is no mention of the KEYZ (qmkW) in the file name. 

@cann0010

**Comment by adf-ncgr** [comment]
yes, I suppose the filenames should contain the dataset keys as with other folders. good catch.
perhaps related: presumably (?) these would validate as gff3 and use that suffix (and might as well
bgzip + tabix index these like the gene_models_main files.

I'll note that these synteny folders as currently structured are a little odd in that we might expect that they will grow over time (ie as new genomes come in for comparison against existing genomes). That's probably not a major concern, as (I guess) the key is not really supposed to be a guarantee of absolute stability of contents of the dataset.

not sure if we need to have any special human readable component of the name like "gene_models_main". My guess is that yucky1.x.yucky2 is as much as needs to be said, but
I certainly wouldn't object to adding a little extra tag like .genome_synteny_main.gff3.gz

**Comment by cann0010** [comment]
I am not sure what "_main" signifies in this case. I vote for the simpler option - i.e. "yucky1.x.yucky2 is as much as needs to be said"

**Comment by adf-ncgr** [comment]
a possible role for a separate main file would be to contain the concatenation of the contents of all
the individual files. Pros: "one stop shop" for all your genomeX synteny questions. Cons: needs to be updated whenever a new comparison is added to the dataset folder. I don't have a strong opinion as I don't really have a clear sense for who among the feds will consume this info.

**Comment by jd-campbell** [comment]
@adf-ncgr @cann0010 
We are going with "yucky1.x.yucky2" but what I do about these two glyma syn files: 
glyma.Wm82_a2_old_duplication.gff.gz
glyma.Wm82_a2_recent_duplication.gff.gz

**Comment by cann0010** [comment]
I recommend this pattern:
glyma.Wm82.gnm2.ann1.x.glyma.Wm82.gnm2.ann1.old_duplication.gff
glyma.Wm82.gnm2.ann1.x.glyma.Wm82.gnm2.ann1.recent_duplication.gff

**Comment by adf-ncgr** [comment]
I don't have any problem with this (except I still think these should be gff3 suffixes!), but would ask the question whether there is any reason we want to put these into separate files rather than maintaining the distinction between old and recent blocks by using an attribute or type field in the gff3 file (my guess is that the proposed model is being suggested by the fact that they have been modeled as separate tracks in the browser and so get dumped as two separate files).

**Comment by cann0010** [comment]
I think this case in soybean derives from the fact that the recent duplication is the main one we wanted to show. The old duplication is fragmented, messy, and less complete.

**Comment by adf-ncgr** [comment]
well, that may be so, but the point I was trying to make is that some "agent" that simply wanted to harvest synteny blocks from the datastore would be put into a similar position of confusion here as those looking in gnm directories and finding multiple fna files or looking in an ann directory and finding multiple gff3 files. Maybe we don't care?

**Comment by cann0010** [comment]
Fair point ... but the option of "doing nothing" here requires doing nothing :-)

**Comment by adf-ncgr** [comment]
ah, looks like I had forgotten that we're putting multiple files into these folders anyway. I guess the hypothetical agent will be slurping them all anyway (or doing nothing in its confusion over the absence of any indicator main file). sounds like my mountainous molehill is collapsing under its own weight...

**Comment by adf-ncgr** [comment]
reopening, as I see @jd-campbell has a lot of unchecked boxes in her list...

**Comment by jd-campbell** [comment]
@cann0010 
In regards to the 
glyma.Wm82.gnm2.ann1.x.glyma.Wm82.gnm2.ann1.old_duplication.gff.gz
and 
glyma.Wm82.gnm2.ann1.x.glyma.Wm82.gnm2.ann1.recent_duplication.gff.gz

We say in the README and MANIFEST.KEYZ.description file we say go back to the genomes original directory/README to get the info you want. But there is no directory or README for the old and recent duplication.  So with your ok I want add this line to the MANIFEST.KEYZ.description for the above two files: 

Review "Multiple whole-genome duplication events" section within Schmutz, J et al. (2010) http://dx.doi.org/10.1038/nature08670"

**Comment by cann0010** [comment]
That sounds OK to me.

**Comment by adf-ncgr** [comment]
@sammyjava I believe you are the only person now who is using these files "programmatically", after I stopped loading them into chado when GCV began generating macrosynteny on the fly. is it your impression that this issue can be closed?

**Comment by sammyjava** [comment]
Well I'm still planning to load synteny blocks into the mines from the datastore, unless you want to put the kibosh on that, which is fine with me. But since the files are in the datastore I was planning to load them. But my issue is https://github.com/legumeinfo/datastore/issues/8 of course, not this one as far as I know.

**Comment by adf-ncgr** [comment]
OK, closing this one which was legislative in nature; will leave legumeinfo/datastore#8 to deal with enforcement.
