### ISSUE TITLE
rehome this repos to LegumeFederationDataStore

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederationDataStore/about_the_data_store#41]
per discussion about the confusing situation engendered by the duplicated content in https://github.com/LegumeFederationDataStore/about_the_data_store

goals:
preserve existing issues
preserve existing revision history/commit logs
achieve new structure and content changes prefigured by the new about_the_data_store repo

@adf-ncgr and @cann0010 will tackle when latter returns from Japan

**Comment by cann0010** [comment]
I believe I have done this successfully.

1. Moved datastore from LegumeFederation to LegumeFederationDataStore, per instructions at https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

2. Clone to local: git clone https://github.com/LegumeFederationDataStore/datastore.git

3. Locally, replace files in datastore with those from about_the_data_store 

4. Register the changes via git
  git rm detect_incongruencies/detect_incongruencies.py detect_incongruencies/incongruency_detector/Detector.py detect_incongruencies/incongruency_detector/Normalizer.py detect_incongruencies/incongruency_detector/__init__.py detect_incongruencies/incongruency_detector/file_helpers.py metadata/about_the_Data_Store.md metadata/about_the_registry.md metadata/adding_data_to_Data_Store.md metadata/template__MANIFEST.KEY.correspondence metadata/template__MANIFEST.KEY.descriptions metadata/template__README.KEY.md.txt private/scripts/add_prefixes_to_gff3.pl private/scripts/expr-dataset-excel-to-md.py private/scripts/make_random_IDs.pl private/scripts/mdsum-folder.bash private/scripts/metadata_md_to_csv.pl 

  git add about_the_Data_Store.md about_the_registry.md adding_data_to_Data_Store.md scripts/ templates/
  git commit -m "Many changes as part of rehoming the repo from LegumeFederation"
  git push origin

  git add .gitignore README.md
  git commit -m "update README and .gitignore as part of rehoming process"
  git push origin

5. Remove about_the_data_store, preparatory to renaming datastore
  Remove the repo via github gui

6. Rename the repo from "datastore" to "about_the_data_store"
  Do this via the gui, from https://github.com/LegumeFederationDataStore/datastore/settings

Net result: there is only one repo, about_the_data_store, in LegumeFederationDataStore/. It seems that issues have come along correctly. @adf-ncgr - please review and close if things look OK.

**Comment by adf-ncgr** [comment]
@ctcncgr I've set permissions so that I think you'll be able to write here now; if you verify this and we all agree we don't really care about preserving the commit histories to this point we can close this.

**Comment by adf-ncgr** [comment]
verified verbally, @ctcncgr is currently working on a feature branch, but should probably merge it into master before we try to get others using the validation scripts. At any rate, this one can be closed.
