### ISSUE TITLE
Create file naming conventions for map files

### ISSUE THREAD

**Issue by ekcannon** [LegumeFederationDataStore/about_the_data_store#43]
Initial proposal:
  <map name>.<uniq>.cmap
Example:
  AA_A.duranensis_x_A.duranensis_a.Z9Z9.cmap

**Comment by adf-ncgr** [comment]
A few questions on the way to standardization:
Is there a reason we want to use "mixed" instead of indicating the 
parents of the cross (where possible)?
also, do we think "map" is sufficient as a type or should we distinguish 
genetic maps from other types of
maps? Is the fifth field considered optional? (doesn't seem to exist in 
"phavu.mixed.map1.7PMp.cmap")

**Comment by ekcannon** [comment]
The periods in the map names are part of Scott K's naming protocols, but they can be changed to dashes and interpreted in the map-display code.

**Comment by cann0010** [comment]
I am no fan of "mixed." I suppose we could do something like "BAT92xJalo" . For some of the Arachis maps, though, the parent names are ugly and complex (names encoding e.g. several generations and a synthetic allotetraploid).

Fifth field: no, I would say that is required - so the phavu filename is non-compliant (and that directory doesn't have MANIFEST files etc.)

The type "map" - I don't mind using that to designate genetic maps - and when other map types come along, they'll need to pick a new symbol.

**Comment by ekcannon** [comment]
So then, would this work?
aradu.aradu.map1.Z9Z9.AA_A-duranensis_x_A-duranensis_a.cmap
OR 
aradu.PI475887_Grif15036.map1.Z9Z9.AA_A-duranensis_x_A-duranensis_a.cmap
OR
aradu.PI475887_X_Grif15036.map1.Z9Z9.AA_A-duranensis_x_A-duranensis_a.cmap

**Comment by cann0010** [comment]
Yes.
I prefer the second one - it being unambiguous but slightly more concise than the third:
aradu.PI475887_Grif15036.map1.Z9Z9.AA_A-duranensis_x_A-duranensis_a.cmap

**Comment by ekcannon** [comment]
Just realized we have some worse examples:

TT_RunnerIAC886_x_A.ipaensis-A.duranensis_a.txt
TT_Florunner_x_A.batizocoi-A.cardenasii-A.diogoi_a

The first is RunnerIAC886 crossed with a two-way intraspecies individual

The second is Florunner crossed with a three-way intraspecies individual defined by (A. batizocoi K9484_x_(A. cardenasii GKP10017_x_ A. diogoi GKP10602))

**Comment by cann0010** [comment]
Yep - the tyranny and quagmire of semantic interpretability. 
For the short genotype prefix, we'd need to some up with something suggestive - maybe
IAC886_x_synthetic
Florunner_x_synthetic
And then the fifth field could be the ugly long map name, I suppose.

**Comment by ekcannon** [comment]
For (perhaps) improved generic-ness, could be:
IAC886_x_infraspecific
Florunner_x_infraspecific

**Comment by cann0010** [comment]
Yes - but I think those examples are inTRAspecific!

**Comment by ekcannon** [comment]
Okay:
`aradu.IAC886_x_intraspecific.map.Z0Z0.TT_RunnerIAC886_x_A*ipaensis-A*duranensis_a.cmap`
`aradu.Florunner_x_intraspecific.map.Z1Z1.TT_Florunner_x_A*batizocoi-A*cardenasii-A*diogoi_a`
Where the *'s will be converted to .'s to get the official map name. 

Uglification indeed!

Now, directory name. For the Phaseolus map, I see:
`Phaseolus_vulgaris/mixed.map1.7PMp/`
`  CHECKSUM.7PMp.md5`
`  README.7PMp.yml`
`  phavu.mixed.map1.7PMp.cmap.txt.gz`
`  phavu.mixed.map1.7PMp.flanking_seq.fna.gz`
`  phavu.mixed.map1.7PMp.map.gff3.gz`
`  phavu.mixed.map1.7PMp.source.xlsx.gz`

Which implies similarly named directories for each map. Ugh. And regrading the number in "map1" ... does this mean the maps will need to be named sequentially? 

So then:
`aradu.IAC886_x_intraspecific.map.Z0Z0`
`  CHECKSUM.Z0Z0.md5'
`  README.Z0Z0.yml`
`  MANIFEST.Z0Z0.correspondence.yml`
`  MANIFEST.Z0Z0.description.yml`
`  aradu.IAC886_x_intraspecific.map.Z0Z0.TT_RunnerIAC886_x_A*ipaensis-A*duranensis_a.cmap`
How in the world will people find the maps they are looking for??

Oy. Uglification++ (Is there any indication of how people are responding to the data store names?)

**Comment by ekcannon** [comment]
Since the cross is in the map name, which fits in the DESCRIPTION field of the file name, could the GENOTYPE field be reduced to species? Eg:
aradu_aradu 
arahy_intraspecific
The map name itself is unique, so further "unique-ification" of the file name isn't necessary. It just breaks the naming convention used by other maps, though not in a big way.

As an alternative, to shorten the names, I could include a xref in the database rather than relying on the the map name being included in the file name. But this would make it even more difficult for someone browsing the data store to find a specific map.

**Comment by adf-ncgr** [comment]
It does seem a bit as though we are trying to take standards developed 
for genomes and force them
somewhat unnaturally onto maps. It's not even clear to me (for example) why
"|aradu.IAC886_x_intraspecific.map.Z0Z0.TT_RunnerIAC886_x_A*ipaensis-A*duranensis_a.cmap"
|would be placed under aradu (rather than araip or arah or the dreaded 
Arachis_sp whose gensp appears to be "mixed")

maybe this is at the point where encoding metadata into file names is 
doing us more harm than good;
perhaps maps will be a good place to test metadata-driven searching 
rather than folder/name based
browsing?

**Comment by ekcannon** [comment]
Sorry! "aradu" was a cutnpaste error.

Could we just drop the genotype field? Or insert a single character so's not to mess up file parsing? For example 'X' for cross, or 'M' for map'. I'm using "arachis" here for A. spp as I don't know it's legfed-approved abbreviation.

`arachis.X.map.Z0Z0/`
`    arachis.X.map.Z0Z0.TT_RunnerIAC886_x_A*ipaensis-A*duranensis_a.cmap`
`    CHECKSUM.Z0Z0.md5` 
`    README.Z0Z0.yml`
`    MANIFEST.Z0Z0.correspondence.yml `
`    MANIFEST.Z0Z0.description.yml `
`    aradu.IAC886_x_intraspecific.map.Z0Z0.TT_RunnerIAC886_x_Aipaensis-Aduranensis_a.cmap`

I don't think the maps need to be numbered, as is suggested by the Phaseolus example (mixed.map**1**.7PMp), as the map name itself will guarantee a unique file name.

**Comment by adf-ncgr** [comment]
what about just putting ""description" where "genotype" is for genomes? 
it seems to
more or less serve the same purpose. I agree with you that there seems 
to be no point
in adding a number after map, as in other cases that is used for 
versioning, which seems
unlikely to be happening here (famous last words)

adf

**Comment by ekcannon** [comment]
This is with the assumption that "description" is optional? That would work well, and would eliminate 3 characters.

`arachis.TT_RunnerIAC886_x_A*ipaensis-A*duranensis_a.map.Z0Z0.cmap`

**Comment by adf-ncgr** [comment]
I'd say if we promote it to reside there, then it is no longer optional; 
seems reasonable to require some indication of
what population a map was produced from.

**Comment by ekcannon** [comment]
I meant using the "genotype" field to hold the map name and leaving out the "description" field.

**Comment by adf-ncgr** [comment]
OK, yes I think we meant the same thing. So what was formerly called description is no longer optional and goes in the 2nd field (after taxonomic designator, before datatype designator).

**Comment by cann0010** [comment]
Can't have asterisks in the name.
I could live with this (no penultimate description field):
  **arahy.TT_RunnerIAC886_x_A_ipaensis-A_duranensis_a.map.Z0Z0.cmap**
Or this (with penultimate description field; I think I prefer that this field be non-optional):
  **arahy.TT_RunnerIAC886_x_A_ipaensis-A_duranensis_a.map.Z0Z0.genetic.cmap**
The fields are:
- Taxonomic designator (gensp)
- Genotype (in this case, a cross)
- Data type (map)
- Key
- Description (maybe optional - though I would vote to make it non-optional)
- Extension

**Comment by ekcannon** [comment]
Oh, right about the asterisks. However, I need some distinct character to indicate .'s so I can translate the file name to a map name. How 'bout #, or ^? Having "genetic" in the description field makes sense as there are multiple types of maps

arahy.TT_RunnerIAC886_x_A^ipaensis-A^duranensis_a.map.Z0Z0.genetic.cmap
arahy.TT_RunnerIAC886_x_A#ipaensis-A#duranensis_a.map.Z0Z0.genetic.cmap

I _think_ I like the ^'s better, but they look odd in a file name.

**Comment by cann0010** [comment]
I'd be most comfortable using only characters allowed in POSIX "Fully portable filenames," using only: A–Z a–z 0–9 . _ -   https://en.wikipedia.org/wiki/Filename

arahy.TT_RunnerIAC886_x_araip-aradu_a.map.Z0Z0.genetic.cmap

How about this - which as the advantage of brevity. Scott's naming protocol would need to change: A.ipaensis --> araip

**Comment by ekcannon** [comment]
Below are the resulting names. If these are deemed acceptable, I'll close this issue. Using "arachis" unless obviously a single species maps. Also using "arachis" for composite maps as many of these are derived from multispecies maps.

arahy.TT_Tifrunner_x_GT-C20_c.map.Z2ST.genetic.cmap
arahy.TT_Florunner_x_araba-araca-aradi_a.map.FQ8V.genetic.cmap
arahy.TT_Fleur11_x_araip-aradu_a.map.C79T.genetic.cmap
arahy.AhConsensus_GautamiFonceka2012_a.map.J0V6.genetic.cmap
arahy.TT_ICGS76_x_CSMG84-1_a.map.VRNN.genetic.cmap
arahy.TT_AhConsensus_GautamiPandey2012_a.map.DBF1.genetic.cmap
arahy.TT_ICGS44_x_ICGS76_a.map.LD1X.genetic.cmap
arachis.BB_araip_x_arama_b.map.YSWF.genetic.cmap
arachis.AA_aradu_x_arast_a.JSWL.genetic.cmap
arahy.TT_VG9514_x_TAG24_a.C78H.genetic.cmap
aradu.AA_aradu_x_aradu_a.82HL.genetic.cmap
arahy.TT_Tifrunner_x_GT-C20_a.4B9C.genetic.cmap
arahy.TT_TAG24_x_ICGV86031_a.BYVP.genetic.cmap
arahy.TT_TG26_x_GPBD4_b.PPD3.genetic.cmap
arachis.AA_aradu_x_arast_b.VZYK.genetic.cmap
arachis.BB_araip_x_arama_a.SM5H.genetic.cmap
arachis.TT_AhConsensus_ShirasawaBertioli2013_a.4C5L.genetic.cmap
arachis.TT_RunnerIAC886_x_araip-aradu_a.P6WF.genetic.cmap
arachis.TT_AhComposite_SujayGowda2012_a.9G9T.genetic.cmap
arahy.TT_TAG24_x_GPBD4_a.L0CZ.genetic.cmap
arahy.TT_TG26_x_GPBD4_a.VB8Z.genetic.cmap
arahy.TT_Tifrunner_x_GT-C20_b.R59G.genetic.cmap

**Comment by adf-ncgr** [comment]
NB: some of the listed names are non-compliant (missing "map" before the 
key); probably an oversight.

question: are we hereby instituting the convention that inter-specific 
data gets tagged with
an unabbreviated genus name? I wonder if it might be better to have some 
explicit indication,
but perhaps that is better accommodated within metadata rather than 
naming convention.
just thinking out loud...

**Comment by ekcannon** [comment]
As things now stand, I'm having to create a separate directory for each map, but some papers have a set of maps, typically 2-3 genetic maps that are used to create a consensus map, for example, the publication GautamiPandey2012. Could these be grouped under a single identifier? If so, what would this look like?

Initial proposal:
```
arachis.GautamiPandey2012.map.VRNN/
   arahy.TT_ICGS76_x_CSMG84-1_a.map.VRNN.genetic.map.cmap
   arachis.TT_AhConsensus_GautamiPandey2012_a.map.VRNN.genetic.cmap
   arahy.TT_ICGS44_x_ICGS76_a.map.VRNN.genetic.cmap
```
An advantage to using our short-hand citation for the second field is that it would make the directory more easily identifiable. However, some sets may be grouped differently, for example, a set of maps associated with a NAM population.

**Comment by cann0010** [comment]
I think there is no problem with grouping several maps in a collection - but I think there's something misinformed in your example (since we are using period to separate "fields"):
arahy.TT_ICGS76_x_CSMG84-1_a.map.VRNN.genetic.map.cmap --> 
arahy.TT_ICGS76_x_CSMG84-1_a.map.VRNN.genetic.cmap

**Comment by ekcannon** [comment]
Resolved. See https://github.com/LegumeFederationDataStore/about_the_data_store/blob/master/about_the_Data_Store.md for agreed-upon map set nomenclature.
