### ISSUE TITLE
Readme in tempaltes/template__README.KEY.yml is not Valid YML

### ISSUE THREAD

**Issue by ctcncgr** [LegumeFederationDataStore/about_the_data_store#54]
The readme template is not valid YML.

The issue is this line:
```
changes:
# Free-text notes about changes to this data collection.
Begin each line with two spaces, a dash, and a space, and a date string: "  - 2018-03-23"
  - 2018-03-23 Removed sections "File Correspondence", "File Checksum", "File List" (these now go in separate files). Added section "Changes".
```

It should be:
```
changes:
# Free-text notes about changes to this data collection. Begin each line with two spaces, a dash, and a space, and a date string: "  - 2018-03-23"
  - 2018-03-23 Removed sections "File Correspondence", "File Checksum", "File List" (these now go in separate files). Added section "Changes".
```
The comment is on multiple lines is read as a key.

**Comment by adf-ncgr** [comment]
is a template file generally required to be a valid instance of the file type that it will become upon being run through the template engine? your legfed koan for the day...

**Comment by adf-ncgr** [comment]
PS. I have no problem with your suggested change. Or if prepending a # to the comment continuation would be valid, that seems slightly less invasive to authorial intent.

**Comment by cann0010** [comment]
Thanks. Fixed.
Incidentally, how should notes be handled in such a list context? I've been doing the following lately:

```
changes:
  - #A note
  - command command command
  - #Another note
  - command command command
```

**Comment by adf-ncgr** [comment]
@cann0010 I have no idea about your question but don't forget to commit and push your change!

**Comment by cann0010** [comment]
@adf-ncgr Thanks for the reminder! Done. Closing.
