### ISSUE TITLE
decide appropriate validation and handling for "badly behaved" gffs

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederationDataStore/about_the_data_store#6]
In the past, I have done some cleaning of gff files received from external sources for things like the misspecification of "phase" info in column 8 leading to erroneous peptide derivations (and other less systematic types of errors). We just encountered a case (revealed by trying to load all species genomes into intermine) in adzuki bean where gene models contain overlapping exons and made it into the legumeinfo chado with this peculiar flavor, e.g.:
```
vigan.Gyeongwon.v3.2    vigan.Gyeongwon.v3.a1   exon    11298526 11298735    .   +   . ID=vigan.Gyeongwon.v3.Vang02g07160.1:exon:4335;Parent=vigan.Gyeongwon.v3.Vang02g07160.1
vigan.Gyeongwon.v3.2    vigan.Gyeongwon.v3.a1   exon    11298732 11298815    .   +   . ID=vigan.Gyeongwon.v3.Vang02g07160.1:exon:4336;Parent=vigan.Gyeongwon.v3.Vang02g07160.1
```

Sam is going to work on some additional validation logic in the intermine loader to prevent these from causing the build to fail, but we probably ought to come to group consensus on how to deal with such things in the datastore.

**Comment by nathanweeks** [comment]
Per @vivekkrish, use the following [GenomeTools](http://genometools.org) options for an initial validation pass:

> ```gt gff3 -sort -tidy -retainids -addids no -checkids yes input.gff3 -o output.gff3```
> * "-sort" orders the features according to hierarchy and other relationships (such as Derives_from)
> * "-tidy" cleans up the file and adds the necessary pragmas (i.e. gff-version, and '###' separator in between groups of features to delineate that anything before the separator has no relationships to features occurring after the separator). If necessary, it also corrects the CDS phase
> * "-retainids" ensures that the original IDs of features are retained (instead of inventing new monotonically ordered IDs)
> * "-addids" adds the 'sequence-region' pragma for each refseqid represented in the file, but doing this would be incorrect since it just finds the (min, max) extent of features on a particular chromosome/scaffold and uses that as the size, which is wrong. Therefore, we set this parameter to no.
> * "-checkids" checks for the uniqueness of all IDs (top-level parent, children and grand-children feaures) within the scope of the file and will error out if there are any issues. So, we set this to yes.
>
> Running through these steps, we get a sanitized file, which when run against gt gff3validator will pass "most" tests.
>
>I say "most" because genometools can't check for issues in attribute values (for example, in your error log, for the Vigna_angularis GFF3 file, it says that the Note attribute value contains a hyphen "=" in it, which has a reserved meaning in the GFF3 spec and needs to be HTML encoded). These have to be checked and fixed by a different tool.

**Comment by adf-ncgr** [comment]
just exploring genometools a bit to sanitize the nascent peanut annotations, I ran across this:
https://github.com/genometools/genometools/wiki/speck-User-manual

which at first glance seems like it might be worth investigating as a way of enforcing some more biologically oriented constraints on our gffs (should we decide that it is appropriate for us to do so- probably can't hurt to at least know what the warts are, even if we choose to accept them).

**Comment by adf-ncgr** [comment]
we've agreed on the outline here, just need to consolidate and disseminate how to ensure we never go crazy again!

**Comment by ctcncgr** [comment]
I'm going to suggest this issue be closed or it is broken out into more specifics.  The incongruency detector now validates gff files using gt and other mechanisms as defined in the data store standard.

Do we still need this general issue open?

**Comment by adf-ncgr** [comment]
yes, @ctcncgr I am going to consider the normalizer/detector strategy sufficient for closing this issue
